package com.example.minibrowser8.model

object StringsHelper {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.UKRAINIAN -> UA_STRINGS[key] ?: EN_STRINGS[key] ?: key
            AppLanguage.RUSSIAN -> RU_STRINGS[key] ?: EN_STRINGS[key] ?: key
            AppLanguage.ENGLISH -> EN_STRINGS[key] ?: key
        }
    }

    private val EN_STRINGS = mapOf(
        "app_title" to "8 Mini Browsers",
        "reload_all" to "↻ RELOAD ALL",
        "settings" to "Settings & Styles",
        "bookmarks" to "Bookmarks",
        "add_bookmark" to "Add Bookmark",
        "bookmark_added" to "Bookmark saved ⭐",
        "bookmark_removed" to "Bookmark removed",
        "no_bookmarks" to "No bookmarks saved yet. Click ⭐ to bookmark any page!",
        "open_in_slot" to "Open in Slot",
        "open_in_all" to "Open in All Slots",
        "delete" to "Delete",
        "url_hint" to "URL / Search…",
        "fullscreen" to "Fullscreen",
        "exit_fullscreen" to "Exit Fullscreen",
        "reload" to "Reload",
        "open_external" to "Open in external browser",
        "desktop_mode" to "Desktop Mode",
        "clear" to "Clear",
        "done" to "Done",
        "active_slots" to "Active Browser Slots",
        "grid_layout" to "Grid Layout",
        "columns_2" to "2 Columns",
        "columns_1" to "1 Column",
        "ui_style" to "UI Theme Style (5 Themes)",
        "language" to "Language / Мова / Язык",
        "presets" to "Preset Feed Bundles",
        "load" to "Load",
        "save" to "Save",
        "title" to "Title",
        "url" to "URL",
        "gemini_ai" to "Gemini AI",
        "gemini_assistant" to "AI Assistant (Gemini)",
        "google_login" to "Sign in to Google",
        "minimize" to "Minimize",
        "close" to "Close"
    )

    private val UA_STRINGS = mapOf(
        "app_title" to "8 Міні Браузерів",
        "reload_all" to "↻ ВСІ",
        "settings" to "Налаштування та Стилі",
        "bookmarks" to "Закладки",
        "add_bookmark" to "Додати закладку",
        "bookmark_added" to "Закладку збережено ⭐",
        "bookmark_removed" to "Закладку видалено",
        "no_bookmarks" to "Закладок ще немає. Натисніть ⭐, щоб додати будь-яку сторінку!",
        "open_in_slot" to "Відкрити у слоті",
        "open_in_all" to "Відкрити у всіх слотах",
        "delete" to "Видалити",
        "url_hint" to "URL / Пошук…",
        "fullscreen" to "Повний екран",
        "exit_fullscreen" to "Вийти з повного екрану",
        "reload" to "Оновити",
        "open_external" to "Відкрити в браузері",
        "desktop_mode" to "Режим ПК",
        "clear" to "Очистити",
        "done" to "Готово",
        "active_slots" to "Активні слоти браузера",
        "grid_layout" to "Розмітка сітки",
        "columns_2" to "2 колонки",
        "columns_1" to "1 колонка",
        "ui_style" to "Стиль інтерфейсу (5 тем)",
        "language" to "Мова / Language / Язык",
        "presets" to "Готові набори сайтів",
        "load" to "Завантажити",
        "save" to "Зберегти",
        "title" to "Назва",
        "url" to "Посилання",
        "gemini_ai" to "Gemini AI",
        "gemini_assistant" to "ШІ-Асистент (Gemini)",
        "google_login" to "Увійти в Google",
        "minimize" to "Згорнути",
        "close" to "Закрити"
    )

    private val RU_STRINGS = mapOf(
        "app_title" to "8 Мини Браузеров",
        "reload_all" to "↻ ВСЕ",
        "settings" to "Настройки и Стили",
        "bookmarks" to "Закладки",
        "add_bookmark" to "Добавить закладку",
        "bookmark_added" to "Закладка сохранена ⭐",
        "bookmark_removed" to "Закладка удалена",
        "no_bookmarks" to "Закладок пока нет. Нажмите ⭐, чтобы сохранить страницу!",
        "open_in_slot" to "Открыть в слоте",
        "open_in_all" to "Открыть во всех слотах",
        "delete" to "Удалить",
        "url_hint" to "URL / Поиск…",
        "fullscreen" to "Полный экран",
        "exit_fullscreen" to "Выйти из полноэкранного режима",
        "reload" to "Обновить",
        "open_external" to "Открыть в браузере",
        "desktop_mode" to "Режим ПК",
        "clear" to "Очистить",
        "done" to "Готово",
        "active_slots" to "Активные слоты браузера",
        "grid_layout" to "Сетка",
        "columns_2" to "2 колонки",
        "columns_1" to "1 колонка",
        "ui_style" to "Стиль интерфейса (5 тем)",
        "language" to "Язык / Language / Мова",
        "presets" to "Готовые наборы сайтов",
        "load" to "Загрузить",
        "save" to "Сохранить",
        "title" to "Название",
        "url" to "Ссылка",
        "gemini_ai" to "Gemini AI",
        "gemini_assistant" to "ИИ-Ассистент (Gemini)",
        "google_login" to "Войти в Google",
        "minimize" to "Свернуть",
        "close" to "Закрыть"
    )
}
